name: etra
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  logger: ^2.5.0
  flutter_staggered_grid_view: ^0.6.2
  provider: ^6.1.2
  fl_chart: ^0.70.2
  syncfusion_flutter_gauges: ^28.1.41
  firebase_core: ^3.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
